logging:
    level:
        ROOT: DEBUG
        com.roberto.controle: DEBUG
        io.github.jhipster: DEBUG

spring:
    profiles:
        active: prod
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/heroku_9b54d3eb431123c?reconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
        username: b2a394ad0f499e
        password: 1d9d0d0a
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
        hibernate:
          ddl-auto: update
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

liquibase:
    contexts: dev
server:
    port: 8080
jhipster:
    http:
        version: V_1_1
    cache:
        ehcache:
            time-to-live-seconds: 3600
            max-entries: 100
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        remember-me:
            key: 61dbdb866b7bb9d48cb395f29d9decc15b138919
    mail:
        from: HasFuel@localhost
        base-url: http://127.0.0.1:8080
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: HasFuel
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            report-frequency: 60
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
application: